# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 20
  - name: Portfolio
    url: portfolio/
    weight: 30
- name: <style="color:red">Amped</style>
    url: https://ampedprivacy.com/
    weight: 40
